# Generated by Django 5.1.3 on 2026-05-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='youtube_link',
            field=models.URLField(max_length=500),
        ),
    ]
