# Generated by Django 5.1.3 on 2026-05-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='youtube_link',
            field=models.TextField(),
        ),
    ]
