# Generated by Django 5.1.3 on 2026-05-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_lesson_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('technology', 'Technology & Development'), ('career', 'Career & Professional Growth'), ('communication', 'Communication & Placement'), ('creativity', 'Creativity & Innovation'), ('others', 'Others')], default='technology', max_length=50),
        ),
    ]
